### ISSUE TITLE
Why does TPS consume metrics from Loggregator?

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/tps#12]
I was interested to learn recently that TPS consumes container metrics from Loggregator [1]. This surprised me, though, as I -- knowing very little about Diego internals -- would have expected TPS to communicate directly with other Diego internals to gain such information.

Is this a design that makes sense for Diego? It seems a little strange to have one part of Diego ask Loggregator for information that another a part of Diego told Loggregator.

[1] See [here](https://github.com/cloudfoundry/tps/blob/1235a69eef73ad455c4c7e40373097983a54faf8/handler/lrpstats/lrpstats.go#L73).

**Comment by MarcPaquette** [comment]
@sethboyles,

Any updates on this 6 year old question or is it okay to close out?

**Comment by sethboyles** [comment]
I suppose we can close it--I personally don't know the answer of whether or not this design makes sense, but it's unlikely to change anytime soon.
